version: '3'
services:
  postgres:
    image: 'postgres'
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
